dist: xenial
language: python
python:
  - "3.6"
install:
  - chmod +x ./install.sh
  - ./install.sh
  - for f in *.ini.example; do mv -- "$f" "${f%.ini.example}.ini"; done # rename all .ini.example files to .ini to verify deployment
script:
  - pylint **/*.py --disable=C,R,W
  - pytest -s tests/