dist: xenial
language: python
python:
  - "3.6"
before_install:
  - chmod +x ./meera.sh
  - sudo ./meera.sh pre-install
install:
  - sudo -H ./meera.sh install
  - sudo ./meera.sh train 5
  - sudo ./meera.sh install-model
script:
  - ./meera.sh lint
  - ./meera.sh evaluate
  - ./meera.sh test
after_script:
  - sudo ./meera.sh clean