dist: xenial
language: python
python:
  - "3.6"
install:
  - chmod +x ./meera.sh
  - ./meera.sh install
  - ./meera.sh train
  - find . -name "*.ini.example" -exec bash -c 'mv "$1" "${1%.ini.example}".ini' - '{}' \; # rename all .ini.example files to .ini to verify deployment
script:
  - ./meera.sh lint
  - ./meera.sh evaluate
  - ./meera.sh test