dist: xenial
language: python
python:
  - "3.6"
install:
  - chmod +x ./meera.sh
  - ./meera.sh pre-install
  - ./meera.sh clean
  - sudo ./meera.sh install
  - ./meera.sh train 5
  - ./meera.sh install-model
script:
  - ./meera.sh lint
  - ./meera.sh evaluate
  - ./meera.sh test