dist: xenial
language: python
python:
  - "3.6"
before_install:
  - chmod +x ./meera.sh
  - chmod +x ./setup.sh
install:
  - sudo ./setup.sh
  - rm -r ./src/nlp/models/*
  - sudo ./meera.sh train 3
script:
  - ./meera.sh lint
  - ./meera.sh evaluate
  - ./meera.sh test
after_script:
  - sudo ./meera.sh clean